//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualFrends {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtualFrends.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT* from Terceros where Email in (SELECT CorreoInvitado from ViewTerceros WHERE EMAIL=@VarId)
        ///union
        ///SELECT* from Terceros where Email in
        ///(SELECT CorreoInvitado from ViewTerceros where Email in (SELECT CorreoInvitado from ViewTerceros WHERE EMAIL=@VarId))
        /// union 
        /// SELECT* from Terceros where Email in
        /// (SELECT CorreoInvitado from ViewTerceros where Email in
        ///((SELECT CorreoInvitado from ViewTerceros where Email in (SELECT CorreoInvitado from ViewTerceros WHERE EMAIL=@VarId))));.
        /// </summary>
        internal static string Matrix {
            get {
                return ResourceManager.GetString("Matrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  SELECT t.* ,&apos;Nivel1&apos;as Nivel ,CAST(CONCAT_WS(&apos; &apos;,t.Apellidos,t.Nombres)as CHAR(250))  as NombreC 
        /// From Terceros t where Email in (SELECT CorreoInvitado from ViewTerceros WHERE EMAIL=@VarId)
        ///union
        ///SELECT t.* ,&apos;Nivel1&apos;as Nivel ,CAST(CONCAT_WS(&apos; &apos;,t.Apellidos,t.Nombres)as CHAR(250))as NombreC
        ///From Terceros t  where Email in
        ///(SELECT CorreoInvitado from ViewTerceros where Email in (SELECT CorreoInvitado from ViewTerceros WHERE EMAIL=@VarId))
        /// union 
        /// SELECT t.* ,&apos;Nivel1&apos;as Nivel ,CAST(CONCAT_WS(&apos; &apos;,t.Ap [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Matrixgeneral {
            get {
                return ResourceManager.GetString("Matrixgeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT t.* ,&apos;Nivel1&apos;as Nivel ,CONCAT_WS(&apos; &apos;,t.Apellidos,t.Nombres) as NombreCompleto From Terceros t where Email in (SELECT CorreoInvitado from ViewTerceros WHERE EMAIL=@VarId)
        ///union
        ///SELECT t.* ,&apos;Nivel1&apos;as Nivel ,CONCAT_WS(&apos; &apos;,t.Apellidos,t.Nombres) as NombreCompleto From Terceros t  where Email in
        ///(SELECT CorreoInvitado from ViewTerceros where Email in (SELECT CorreoInvitado from ViewTerceros WHERE EMAIL=@VarId))
        /// union 
        /// SELECT t.* ,&apos;Nivel1&apos;as Nivel ,CONCAT_WS(&apos; &apos;,t.Apellidos,t.Nombres) as NombreComp [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string MatrixNivel {
            get {
                return ResourceManager.GetString("MatrixNivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT * from Terceros where  email in
        ///(
        ///SELECT CorreoAnfitrion from Referidos where CorreoInvitado in
        ///(
        ///SELECT CorreoAnfitrion from Referidos where CorreoInvitado in
        ///(
        ///SELECT CorreoAnfitrion from Referidos where CorreoInvitado=@varid
        ///)
        ///)
        ///).
        /// </summary>
        internal static string MiMatrix {
            get {
                return ResourceManager.GetString("MiMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT
        ///if(sum(d.Credito-d.Debito) is null,0,sum(Credito-Debito)) as Saldo
        /// from Diario d
        /// JOIN Operaciones o on o.Id=d.IdOperacion
        /// WHERE d.Email=@VarId
        /// and Estado=1.
        /// </summary>
        internal static string SaldoDiario {
            get {
                return ResourceManager.GetString("SaldoDiario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT
        ///d.Fecha,
        ///d.IdTransaccion,
        ///o.Operacion,
        ///d.Concepto,
        ///d.Credito-d.Debito  Valor,
        ///d.Codigo,
        ///d.EmailOperacion 
        /// from Diario d
        /// JOIN Operaciones o on o.Id=d.IdOperacion
        /// WHERE d.Email=@VarId.
        /// </summary>
        internal static string ViewDiario {
            get {
                return ResourceManager.GetString("ViewDiario", resourceCulture);
            }
        }
    }
}
